Orthogonal Vectors

In [1]:
import numpy as np

In [2]:
#buat vector i dengan elemen (1,0)
i = np.array([1, 0])
i

array([1, 0])

In [3]:
#buat vector j dengan elemen (0,1)
j = np.array([0, 1])
j

array([0, 1])

In [4]:
np.dot(i, j)

np.int64(0)

In [6]:
# Bukti Orthogonal: Hitung Dot Product antara i dan j
# Rumus: (1*0) + (0*1) = 0
dot_product = np.dot(i, j)

print("Dot Product i dan j:", dot_product)

if dot_product == 0:
    print("Kesimpulan: Vektor i dan j adalah Orthogonal.")
else:
    print("Kesimpulan: Vektor i dan j tidak Orthogonal.")

Dot Product i dan j: 0
Kesimpulan: Vektor i dan j adalah Orthogonal.


Orthogonal Vectors

In [7]:
import numpy as np

In [9]:
# Membuat vektor v
v = np.array([1, 2])
v

array([1, 2])

In [10]:
# Membuat vektor w
w = np.array([2, -1])
w


array([ 2, -1])

In [11]:
# Bukti Orthogonal: Hitung Dot Product antara v dan w
# Rumus: (1*2) + (-2*1) = 0
dot_product = np.dot(v, w)

print("Dot Product v dan w:", dot_product)

if dot_product == 0:
    print("Kesimpulan: Vektor v dan w adalah Orthogonal.")
else:
    print("Kesimpulan: Vektor v dan w tidak Orthogonal.")


Dot Product v dan w: 0
Kesimpulan: Vektor v dan w adalah Orthogonal.
