Matrices (Rank 2 Tensors) in NumPy

In [1]:
import numpy as np

In [2]:
# Membuat matrix X berukuran 2x3 menggunakan numpy
x = np.array([[1,10,8],[11,18,81]])
x

array([[ 1, 10,  8],
       [11, 18, 81]])

In [3]:
# Menampilkan ukuran matriks x
x.shape

(2, 3)

In [5]:
#  Menampilkan seluruh elemen dari kolom pertama matriks x
x[:, 0]

array([ 1, 11])

In [6]:
#  Menampilkan seluruh elemen dari baris kedua matriks x
x[1, :]

array([11, 18, 81])

Matrices in PyTorch

In [7]:
import torch

In [8]:
# Membuat matrix X berukuran 2x3 menggunakan torch
x_pt = torch.tensor([[1,10,8],[11,18,81]])
x_pt

tensor([[ 1, 10,  8],
        [11, 18, 81]])

In [9]:
# Menampilkan ukuran matriks x
x_pt.shape

torch.Size([2, 3])

In [11]:
#  Menampilkan seluruh elemen dari kolom pertama matriks x dengan PyTorch
x_pt[:, 0]

tensor([ 1, 11])

In [12]:
#  Menampilkan seluruh elemen dari baris kedua matriks x dengan Pytorch
x_pt[1, :]

tensor([11, 18, 81])

Matrices in TensorFlow

In [14]:
import tensorflow as tf

In [15]:
# Membuat matriks X berukuran 2x3 dengan TensorFlow
x_tf = tf.Variable([[1,10,8],[11,18,81]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 1, 10,  8],
       [11, 18, 81]], dtype=int32)>

In [16]:
# Menampilkan ukuran matriks x
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [17]:
#  Menampilkan seluruh elemen dari kolom pertama matriks x dengan tensorflow
x_tf[:, 0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 11], dtype=int32)>

In [18]:
#  Menampilkan seluruh elemen dari baris kedua matriks x dengan tensorflow
x_tf[1, :]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 18, 81], dtype=int32)>