Vector

In [1]:
import numpy as np

In [3]:
# Membuat vektor v ukuran 3x1
x = np.array([11, 18, 10])
x


array([11, 18, 10])

In [4]:
# Hitung panjang vector x
print(len(x))

3


In [5]:
# Tampilkan ukuran vector x
print("Ukuran vector x:", x.shape)

Ukuran vector x: (3,)


In [6]:
# Tampilkan tipe data dari vector x
print("Tipe data vector x:", type(x))

Tipe data vector x: <class 'numpy.ndarray'>


In [7]:
# Akses elemen pertama dari vector x
print("Elemen pertama:", x[0])

Elemen pertama: 11


In [8]:
# Tampilkan tipe data elemen pertama dari vector x
print("Tipe data elemen pertama:", type(x[0]))

Tipe data elemen pertama: <class 'numpy.int64'>


Vector Transposition

In [9]:
# Buat vector baris x (ukuran 1x3) agar bisa ditranspose menjadi 3x1
x_t = x.T
x_t

array([11, 18, 10])

In [10]:
# Tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [12]:
# Buat vector y (ukuran 1x3)
y = np.array([[81, 8, 11]])
y

array([[81,  8,  1]])

In [16]:
# transpose vektor y
y_t

array([[81],
       [ 8],
       [ 1]])

In [17]:
# Tampilkan ukuran dari vector x_t
y.shape

(1, 3)